version: '3.8'

services:
  # Oracle Database
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe-prolink
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=ProLink123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./create-tables-oracle.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "sys/ProLink123@XEPDB1 as sysdba", "<<<", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ProLink Backend
  prolink-backend:
    build:
      context: ./prolink-backend
      dockerfile: Dockerfile
    container_name: prolink-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521:XEPDB1
      - SPRING_DATASOURCE_USERNAME=prolink
      - SPRING_DATASOURCE_PASSWORD=ProLink123
    depends_on:
      oracle-db:
        condition: service_healthy
    restart: unless-stopped

  # Frontend Server (Nginx)
  prolink-frontend:
    image: nginx:alpine
    container_name: prolink-frontend
    ports:
      - "3000:80"
    volumes:
      - ./prolink-app.html:/usr/share/nginx/html/index.html
      - ./test-buttons.html:/usr/share/nginx/html/test.html
    restart: unless-stopped

volumes:
  oracle_data:
    driver: local