-- Script para crear usuario ProLink en Oracle
CREATE USER prolink IDENTIFIED BY ProLink123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO prolink;
GRANT CREATE SESSION TO prolink;
GRANT CREATE TABLE TO prolink;
GRANT CREATE SEQUENCE TO prolink;
GRANT CREATE VIEW TO prolink;
GRANT CREATE PROCEDURE TO prolink;
GRANT CREATE TRIGGER TO prolink;
GRANT SELECT ANY DICTIONARY TO prolink;
GRANT CREATE ANY INDEX TO prolink;
GRANT ALTER ANY TABLE TO prolink;

COMMIT;

SELECT 'Usuario ProLink creado exitosamente' AS RESULTADO FROM dual;
EXIT;